### ISSUE TITLE
Data Sync

### ISSUE THREAD

**Issue by mobileonekh** [378056350/bookkeeping-iOS#2]
Hi, how your data is stored on the device? how is your data sync?
Is it using Realm, firebase or some other custom built?

Thanks;

**Comment by 378056350** [comment]
Originally I used third-party storage, but I found that the data could not be synchronized in the Widget, it was changed to nsuserdefaults (a bit awkward)

**Comment by mobileonekh** [comment]
For this kind of app, user's data is important. So data sync is very important. So my suggestion is either to use Cloudkit, Parse, Realm or Firebase. The choice depend on your app data structure/requirement.

**Comment by 378056350** [comment]
You are right, but I failed when trying to interoperate with Widget data... plus Chinese New Year, I am lazy, I will modify it later.
The above words are translated by Google. If you don't understand, please forgive me.
