### ISSUE TITLE
打开工程运行不了

### ISSUE THREAD

**Issue by JackLeeMing** [378056350/bookkeeping-iOS#3]
![Uploading QQ20190315-101344@2x.png…]()

**Comment by 378056350** [comment]
你的图挂了，我看不到，pod install了？报的什么错？

**Comment by JackLeeMing** [comment]
<img width="1514" alt="QQ20190315-101344@2x" src="https://user-images.githubusercontent.com/8730975/54423889-a900cf80-474c-11e9-92d4-000f34e61627.png">

**Comment by JackLeeMing** [comment]
您帮看看，头一次遇到类似错误

**Comment by 378056350** [comment]
> 您帮看看，头一次遇到类似错误

抱歉，回复的有点晚，不要打我

小组件（widget）问题，需要在证书配置里添加配置，不愿意添加的话，直接删除掉两个小组件即可运行

**Comment by JackLeeMing** [comment]
ok, 谢谢。新手研究借鉴一下阁下的项目

**Comment by 378056350** [comment]
> ok, 谢谢。新手研究借鉴一下阁下的项目

没什么可借鉴的，时间仓促写的比较急，如果是为了毕业设计...小心和别人重复，之前有人为了这个加我
如果是研究功能，请百度 code4app，按功能学习😊
